# Generated by Django 6.0.5 on 2026-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_size',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
